<form class="log-in-form"
  action="<?=App::config('url')?>index/autorizacija"
  method="POST">
  <h4 class="text-center">Prijava</h4>
  <label>Email
  <input type="email" name="email" value="<?=$email?>">
  </label>
  <label>Lozinka
  <input type="password" name="lozinka">
  </label>
  <input type="submit" class="button expanded" value="Prijava">

  <p class="text-center"><?=$poruka?></p>
</form>


