<nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="<?=App::config('url')?>"><strong>Dental</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <?php if(isset($_SESSION['autoriziran'])): ?>
          <li><a href="<?=App::config('url')?>nadzornaploca/index">Nadzorna ploča</a></li>
          <li><a href="<?=App::config('url')?>index/era">ERA</a></li>
          <li><a href="<?=App::config('url')?>stomatolog/index">Stomatolozi</a></li> 
          <li><a href="<?=App::config('url')?>pacijent/index">Pacijenti</a></li> 
          <li><a href="<?=App::config('url')?>termin/index">Termini</a></li>
          <li><a href="<?=App::config('url')?>ordinacija/index">Ordinacije</a></li>          
        <?php if($_SESSION['autoriziran']->uloga=='admin'): ?>
          <li><a href="#">Operateri</a></li>
        <?php endif;?>
        <?php endif;?>
        <?php if(!isset($_SESSION['autoriziran'])): ?>
          <li><a href="<?=App::config('url')?>">Početna</a></li>
          <li><a href="<?=App::config('url')?>index/novosti">Novosti</a></li>
          <li><a href="<?=App::config('url')?>index/usluge">Usluge</a></li>  
        <?php endif;?>
        <li>
          <?php if(!isset($_SESSION['autoriziran'])): ?>
            <a href="<?=App::config('url')?>index/login">Prijavi se</a>
          <?php else: ?>
            <a href="<?=App::config('url')?>index/logout">
          <?=$_SESSION['autoriziran']->ime?> 
          <?=$_SESSION['autoriziran']->prezime?> Odjava</a>
          <?php endif;?>
        </li>
      </ul>
    </div>
  </div>
</nav>

