<nav class="top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" href="<?=App::config('url')?>"><strong>Dental</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <li><a href="<?=App::config('url')?>">Početna</a></li>
        <li><a href="<?=App::config('url')?>index/novosti">Novosti</a></li>
        <li><a href="#">Usluge</a></li>
        <li><a href="#">O nama</a></li>
        <li>
        <a href="<?=App::config('url')?>index/login">Prijavi se</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

