<form class="log-in-form"
  action="<?=App::config('url')?>usluga/novo"
  method="POST">
  <h4 class="text-center">Dodavanje nove usluge</h4>
    <label>Naziv
      <input type="text" name="naziv" value="<?=$usluga->naziv?>">
    </label>
      <label>Vrsta
        <input type="text" name="vrsta" value="<?=$usluga->vrsta?>">
      </label>
    <label>cijena
      <input type="text" name="cijena" value="<?=$usluga->cijena?>">
    </label>
  <p><input type="submit" class="button expanded" value="Dodaj"></input></p>
    <?=$poruka?>
</form>