<table class="unstriped stack">
    <thead>
        <h4 style="text-align: center;">Baza stomatologa</h4>
        </br>
        <tr>
            <th>Ime i prezime stomatologa</th>
            <th>Specijalizacija</th>
            <th>Email</th>
            <th style="text-align: justify;">
            <a href="<?=App::config('url')?>stomatolog/novo">Dodaj stomatologa</a>
            </th>
        </tr>
    </thead>
    <tbody>
     <?php foreach($entiteti as $red): ?>
        <tr>
            <td><?=$red->ime?> <?=$red->prezime?></td>
            <td><?=$red->specijalizacija?></td>
            <td><?=$red->email?></td>
            <td>
                <a href="<?=App::config('url')?>stomatolog/promjena">
                  <i title="promjena" class="fas fa-2x fa-edit" ></i></a>      
                <a href="<?=App::config('url')?>stomatolog/brisanje">
                  <i title="brisanje" style="color: red" class="fas fa-2x fa-trash-alt"></i></a>
            </td>
     <?php endforeach; ?>
        </tr>
    </tbody>
</table>


