<table class="unstriped stack">
    <thead>
        <h4 style="text-align: center;">Baza stomatologa</h4>
        </br>
        <tr>
            <th>Ime i prezime stomatologa</th>
            <th>Specijalizacija</th>
            <th>Email</th>
            <th>Ordinacija</th>
            <th>
            <a href="<?=App::config('url')?>stomatolog/novo">
              <i title="dodaj novog stomatologa" class="fas fa-2x fa-plus-square" style="color: green"></i>
            </a>
            </th>
        </tr>
    </thead>
    <tbody>
     <?php foreach($entiteti as $entitet): ?>
        <tr>
          <td><?=$entitet->ime. ' ' .$entitet->prezime?></td>
          <td><?=$entitet->specijalizacija?></td>
          <td><?=$entitet->email?></td>
          <td><?=$entitet->ordinacija?></td>
          <td>
            <a href="<?=App::config('url')?>stomatolog/promjena?sifra=<?=$entitet->sifra?>">
                <i title="promjena" class="fas fa-2x fa-edit" ></i></a>

            <?php if($entitet->ukupnotermina==0): ?>
            <a href="<?=App::config('url')?>stomatolog/brisanje?sifra=<?=$entitet->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$entitet->ime?>  <?=$entitet->prezime?>?');">
                <i title="brisanje" style="color: red" class="fas fa-2x fa-trash-alt"></i></a>
            <?php endif; ?>
            </td>
     <?php endforeach; ?>
        </tr>
    </tbody>
</table>


