<form class="log-in-form" 
    action="<?=App::config('url')?>stomatolog/novo"
    method="POST">
  <h4 class="text-center">Unos novog stomatologa</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Ime
          <input type="text" name="ime" value="<?=$entitet->ime?>">
        </label>
    </div>
    <div class="cell large-6">
      <label>Prezime
        <input type="text"  name="prezime" value="<?=$entitet->prezime?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Specijalizacija
        <input type="text" name="specijalizacija" value="<?=$entitet->specijalizacija?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Email
        <input type="email" name="email" value="<?=$entitet->email?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Grad
        <input type="text" name="grad" value="<?=$entitet->grad?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Adresa
        <input type="text" name="adresa" value="<?=$entitet->adresa?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Kontakt
        <input type="text" name="kontakt" value="<?=$entitet->kontakt?>">
      </label>
    </div>
  </div>
   
  

   <p class="text-center"><?=$poruka?></p>

  <div class="grid-x grid-padding-x">
    <div class="cell small-6 medium-6 large-6">
      <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
    <div class="cell small-6 medium-6 large-6">
      <a class="alert button expanded" 
      href="<?=App::config('url')?>stomatolog/index">Nazad</a>
    </div>
  </div>
</form>