<form class="log-in-form" 
    action="<?=App::config('url')?>stomatolog/promjena"
    method="POST">
  <h4 class="text-center">Izmjena podataka stomatologa</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
        <label>Ime
          <input type="text" name="ime" value="<?=$entitet->ime?>">
        </label>
    </div>
    <div class="cell large-6">
      <label>Prezime
        <input type="text"  name="prezime" value="<?=$entitet->prezime?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Specijalizacija
        <input type="text" name="specijalizacija" value="<?=$entitet->specijalizacija?>">
      </label>
    </div>
    <div class="cell large-6">
      <label>Email
        <input type="email" name="email" value="<?=$entitet->email?>">
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
    <label>Ordinacija
      <select name="ordinacija">
          <?php foreach($ordinacije as $ordinacija): ?>
            <option <?php 
              if($entitet->ordinacija==$ordinacija->sifra){
                echo ' selected="selected" ';
              }
              ?> value="<?=$ordinacija->sifra ?>"><?=$ordinacija->grad . ' ' . $ordinacija->adresa; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>
   
  

   <p class="text-center"><?=$poruka?></p>

  <div class="grid-x grid-padding-x">
    <div class="cell small-6 medium-6 large-6">
      <input type="submit" class="button expanded" value="Promjeni"></input>
    </div>
    <div class="cell small-6 medium-6 large-6">
      <a class="alert button expanded" 
      href="<?=App::config('url')?>stomatolog/index">Nazad</a>
    </div>
  </div>
  <input type="hidden" name="sifra" value="<?=$entitet->sifra?>">
</form>
  