<table class="unstriped stack">
    <thead>
        <h4 style="text-align: center;">Baza pacijenata</h4>
        </br>
        <tr>
            <th>Ime i prezime pacijenta</th>
            <th>Email</th>
            <th>
            <a href="<?=App::config('url')?>pacijent/novo">
                <i title="dodaj novog pacijenta" class="fas fa-2x fa-plus-square" style="color: green"></i>
            </a>
            </th>
        </tr>
    </thead>
    <tbody>
     <?php foreach($entiteti as $red): ?>
        <tr>
          <td><?=$red->ime?> <?=$red->prezime?></td>
          <td><?=$red->email?></td>
          <td>
            <a href="<?=App::config('url')?>pacijent/promjena?sifra=<?=$red->sifra?>">
                <i title="promjena" class="fas fa-2x fa-edit" ></i></a>

            <?php if($red->ukupnotermina==0): ?>
            <a href="<?=App::config('url')?>pacijent/brisanje?sifra=<?=$red->sifra?>"
            onclick="return confirm('Sigurno obrisati <?=$red->ime?>  <?=$red->prezime?>?');">
                <i title="brisanje" style="color: red" class="fas fa-2x fa-trash-alt"></i></a>
            <?php endif; ?>
            </td>
     <?php endforeach; ?>
        </tr>
    </tbody>
</table>