<table class="unstriped stack">
    <thead>
        <h4 style="text-align: center;">Termini</h4>
        <tr>
            <th>Pacijent</th>
            <th>Stomatolog</th>
            <th>Specijalizacija</th>
        </tr>
    </thead>
    <tbody>
     <?php foreach($entiteti as $red): ?>
        <tr>
          <td><?=$red->pacijent?></td>
          <td><?=$red->stomatolog?></td>
          <td><?=$red->specijalizacija?></td>
     <?php endforeach; ?>
        </tr>
    </tbody>
</table>