<form class="log-in-form" 
    action="<?=App::config('url')?>termin/novo"
    method="POST">
  <h4 class="text-center">Dodavanje novog termina</h4>



  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Pacijent
        <select name="pacijent">
          <?php foreach($pacijenti as $pacijent): ?>
            <option <?php if($entitet->pacijent==$pacijent->sifra)
                {
                echo ' selected="selected" ';
                }
                ?> value="<?=$pacijent->sifra ?>"><?=$pacijent->ime . ' ' . $pacijent->prezime; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>

  <div class="grid-x grid-padding-x">
    <div class="cell large-6">
      <label>Stomatolog
      <select name="stomatolog">
          <?php foreach($stomatolozi as $stomatolog): ?>
            <option <?php if($entitet->stomatolog==$stomatolog->sifra)
                {
                    echo ' selected="selected" ';
                }
                ?> value="<?=$stomatolog->sifra ?>"><?=$stomatolog->ime . ' ' . $stomatolog->prezime; ?></option>
          <?php endforeach; ?>
        </select>
      </label>
    </div>
  </div>
  
 
<div class="grid-x grid-padding-x">
    <div class="cell">
     <div class="callout">
     <p class="text-center"><?=$poruka?></p>
     </div>
    </div>
  </div>
  

<div class="grid-x grid-padding-x">
  <div class="cell small-6 medium-6 large-6">
    <input type="submit" class="button expanded" value="Dodaj"></input>
  </div>
  <div class="cell small-6 medium-6 large-6">
    <a class="alert button expanded" 
        href="<?=App::config('url')?>termin/index">Nazad</a>
  </div>
</div>

</form>